spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin@mysql

server:
  port: 8000